"""
Django settings for emart project. 

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8o353)z(_*^04+jhey!m*q3_no@vhn*7v8(6xz4rl6=kunu=it'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1' ,'68.183.84.217', 'emartshop.site', 'www.emartshop.site']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',

    # paypal integration
    'paypal.standard.ipn'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'emart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'emart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static/'
#MEDIA_URL  , MEDIA_ROOT -->iske bad APP--> ka url.py me Settings,static,path
#add karte hai tabhi upload_image --> ka submition work karega
MEDIA_URL='/media/'
MEDIA_ROOT= BASE_DIR/'media'
# login karte wquit accounts/profile me na jakar --> sirf (profile ) url me jaye to uske liye
#login redirect url define karna padega --> profile page ka
# ab error nahi dega
LOGIN_REDIRECT_URL='/profile/'
#iske bad hume karna hai (Rakesh) humesa dikh raha  jo ki login ke bad dikhna chahiye
#Cart --> bhi hamara public nahi rahega(login ke bad dikhna chahiye)
# (Login) and (Registration) Login ke pahle dikhna chahiye ye 3 kam karna hai
#base.html -->se karenge (navigation bar humara yaha hai)
LOGOUT_REDIRECT_URL='login'
# ye Terminal me Link provide karta hai Password Reset ke liye
# EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'
# session engine db ho jaye uske liye
SESSION_ENGINE = "django.contrib.sessions.backends.db"


PAYPAL_RECEIVER_EMAIL='emartseller134@gmail.com'
PAYPAL_TEST=True


#email settings

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'rakesh.kumar.cse23@heritageit.edu.in'
# EMAIL_HOST_USER = 'emartwebmain@gmail.com'
EMAIL_HOST_PASSWORD = 'l4XW1ZaO'
# EMAIL_HOST_PASSWORD = 'AbcdAbcd@1234'